stages:
- name: buildimage
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: cuijx/node-web-app:${CICD_EXECUTION_SEQUENCE}}
      pushRemote: true
      registry: index.docker.io
  when:
    branch:
      include:
      - main
    event:
      include:
      - push
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
  when:
    branch:
      include:
      - main
    event:
      include:
      - push
timeout: 60
notification: {}
