apiVersion: v1
kind: Service
metadata:
  name: node-web-app
  labels:
    app: node-web-app
spec:
  ports:
  - name: app
    port: 8080
  selector:
    app: node-web-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app
  labels:
    app: node-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-web-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: node-web-app
    spec:
      containers:
      - image: cuijx/node-web-app:${CICD_GIT_COMMIT}
        imagePullPolicy: IfNotPresent
        name: node-web-app
        ports:
        - containerPort: 8080
          name: app
